# -*- coding: utf-8 -*-
"""prakalgo7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uRKe294-ztOBz9faaBGIW87aXFtVNA3f
"""

def hitung_faktorial(n):
    if n < 0:
        return "Faktorial tidak dapat dihitung untuk bilangan negatif."
    elif n == 0 or n == 1:
        return 1
    else:
        hasil = 1
        for i in range(2, n + 1):
            hasil *= i
        return hasil
bilangan = int(input("nilai: "))
print(f"Faktorial dari {bilangan} adalah {hitung_faktorial(bilangan)}")

def hitung_vokal_dan_konsonan(kalimat):
    jumlah_vokal = 0
    jumlah_konsonan = 0
    kalimat = kalimat.lower()
    for karakter in kalimat:
        if karakter.isalpha():
            if karakter in 'aeiou':
                jumlah_vokal += 1
            else:
                jumlah_konsonan += 1
    return jumlah_vokal, jumlah_konsonan
kalimat_input = input("Masukkan sebuah kalimat: ")
vokal, konsonan = hitung_vokal_dan_konsonan(kalimat_input)
print(f"Jumlah huruf vokal: {vokal}")
print(f"Jumlah huruf konsonan: {konsonan}")

def kubik(angka):
    return angka ** 3

def cek_habis_dibagi_tiga(angka):
    if angka % 3 == 0:
        hasil_kubik = kubik(angka)
        return hasil_kubik
    else:
        return "False"

# Contoh penggunaan:
angka_input = int(input("Masukkan angka: "))
hasil = cek_habis_dibagi_tiga(angka_input)

print("Hasil:", hasil)

def kubik(angka):
    return angka**3

def cek_habis_dibagi_tiga(angka):
    if angka % 3 == 0:
        return kubik(angka)
    else:
        return False

# Meminta input dari pengguna
input_angka = int(input("Masukkan suatu angka: "))

# Memanggil fungsi kedua dan menampilkan hasil
hasil = cek_habis_dibagi_tiga(input_angka)
if hasil is not False:
    print(f"Nilai kubik dari {input_angka} adalah {hasil}")
else:
    print("False")